export enum FieldType {
    Unknown = 'Unknown',
    Static = 'Static',
    TextBox = 'TextBox',
    Number = 'Number',
    EmailAddress = 'EmailAddress',
    Phone = 'Phone',
    TextArea = 'TextArea',
    RichText = 'RichText',
    Date = 'Date',
    Time = 'Time',
    DateTime = 'DateTime',
    Select = 'Select',
    MultiSelect = 'MultiSelect',
    RadioButton = 'RadioButton',
    MultiSelectCheckBox = 'MultiSelectCheckBox',
    FileAttachment = 'FileAttachment',
    Image = 'Image',
    Password = 'Password',
    Hidden = 'Hidden',
    CheckBox = 'CheckBox',
    Currency = 'Currency',
    Url = 'Url',
    CreditCard = 'CreditCard',
    Custom = 'Custom',
    KeyField = 'KeyField',
    CheckBoxMatrix = 'CheckBoxMatrix'
}
