name: .NET

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Restore Build and Test
      run: |
        chmod +x ./build.sh
        ./build.sh ${{github.run_number}}
    - name: Inspect Publish 1
      run: |       
        pwd
        ls
    - name: Inspect Publish 2
      run: |       
        ls ./release
        ls ./release/nuget/
    - name: Publish
      run: |       
        dotnet nuget push ./release/nuget/*.nupkg -k ${{secrets.NUGET_API}} -s https://api.nuget.org/v3/index.json
